### ISSUE TITLE
SDK Brower Login Took A Long Time

### ISSUE THREAD

**Issue by adminempower** [plivo/plivo-browser-sdk2-examples#100]
Hi Everyone, Please see the link https://s3.amazonaws.com/plivobrowsersdk/v2/example.html

**Comment by eniyavanm** [comment]
@adminempower Can we know whether you are not able to login with the Plivo Endpoint or the S3 link that we had hosted is not working for you.

For more questions and faster support contact support@plivo.com

**Comment by adminempower** [comment]
@eniyavanm 
I setup in my local server by doing below:
git clone https://github.com/plivo/plivo-browser-sdk2-examples.git
npm install
npm start

At first I thought, the issue is with my local setting.  So  visit the live demo below:
https://s3.amazonaws.com/plivobrowsersdk/v2/example.html

I found out that live demo is not working either during login. If you input wrong credentials it will prompt right away. But if you input a correct one. I will show a loading indicator that never ends or stops.

https://user-images.githubusercontent.com/79679151/109265019-d616f180-7840-11eb-876f-66e44f24f94f.mp4

**Comment by eniyavanm** [comment]
@adminempower 
"xxxempower. associates" doesn't seem to be a valid endpoint. Was this endpoint created in the Plivo console?
For more questions and faster support contact support@plivo.com

**Comment by adminempower** [comment]
I go the link from the document saying "visit live demo". I am assuming that logging using Plivo credentials this will work.
I also install this in my local instance they have the same behavior. Do I have to do something else before I can use the live demo?

**Comment by aparajita-dutta** [comment]
Hi Ryan, 

You can refer to this document to know how to register an endpoint: https://support.plivo.com/hc/en-us/articles/360041854131-How-do-I-register-an-endpoint-on-my-VoIP-or-softphone- 

Also, we have updated the ticket: https://plivo.zendesk.com/agent/tickets/41792 with the details. Please do let us know in the ticket if you have any further queries.

**Comment by eniyavanm** [comment]
Closing this as there is Support ticket
