### ISSUE TITLE
Unable to login into the plivo chrome app 

### ISSUE THREAD

**Issue by jspring9** [plivo/plivo-browser-sdk2-examples#117]
![image](https://user-images.githubusercontent.com/1026325/171963154-e65594fa-fdcc-4325-a923-1459ebb1dd87.png)

![image](https://user-images.githubusercontent.com/1026325/171963191-a1da063f-889b-49f2-9cb9-4ef726278392.png)

I believe my credentials are correct.

**Comment by mprince2k18** [comment]
any solution of this error?

**Comment by mprince2k18** [comment]
its been 3 years man.

**Comment by jpca999** [comment]
Leave Plivo , they dont care.

**Comment by AndreyZ1** [comment]
you have to create endpoint first and then use username and password, then it will work

**Comment by huzaif-plivo** [comment]
@jspring9 Sorry for missing this request. To login and begin making calls, you must first create an endpoint in your [console](https://console.plivo.com/voice/endpoints/) and use the credentials from that endpoint as your username and password.
Reference: https://www.plivo.com/docs/voice/concepts/sip-endpoint

If you have any more questions, please contact our [support team](https://help.plivo.com/hc/en-us) for prompt assistance.
