### ISSUE TITLE
onCallRemoteRinging is never called

### ISSUE THREAD

**Issue by sryze** [plivo/plivo-browser-sdk2-examples#4]
I'm using an `onCallRemoteRinging` handler to get the CallUUID of the call to store some information about the call before the answer URL is requested by Plivo (to work around the inability to pass parameters to Answer URL, see https://github.com/plivo/plivo-websdk-2.0-example/issues/2).

For some reason it just stopped working. It used to be called somewhere between `client.call()` and answer URL but now it's not. I can still make outgoing calls from the browser.

This is really frustrating because I don't see any errors in the logs, so I can only guess what's wrong with my setup.

**Comment by SivaPlivo** [comment]
@sryze Thank you for reaching out to us and your interest in Plivo Browser SDK. We just looked into this and found that it is mostly happening with 
![screen shot 2018-01-09 at 5 31 28 pm](https://user-images.githubusercontent.com/26872159/34720279-21f06360-f564-11e7-962b-f0dccd247d2d.png)
GSM or PSTN calls. If you make outbound calls to SIP endpoints "onCallRemoteRinging" handler will be called. Give us some time, will get back to you ASAP.

**Comment by eniyavanm** [comment]
@sryze 
Please refer to our latest example
