### ISSUE TITLE
Google Chrome Doesn't ring on inactif tab

### ISSUE THREAD

**Issue by Nanard** [plivo/plivo-browser-sdk2-examples#87]
When receiving a phone call, there is no sound on google chrome if the tab is not actif.

Tested on Version 87.0.4280.67 (Build officiel) (x86_64)

**Comment by eniyavanm** [comment]
@Nanard This is fixed with the latest SDK version. Please refer https://www.plivo.com/docs/sdk/client/browser/changelog/
